### ISSUE TITLE
Tag 1.2.0-RC1

### ISSUE THREAD

**Issue by ryandesign** [w8tvi/dircproxy#82]
[1.2.0-RC1 was released January 9, 2009](https://web.archive.org/web/20150331012707/http://code.google.com/p/dircproxy/downloads/list) but there is no tag for it in this repository. The latest tag here is RELEASE-1_2_0-BETA. Could a RELEASE-1_2_0-RC1 tag be created? Looks like the correct commit to use for that tag would be 4cc72492b9166edaf58695ac924aec4d03106f63.

**Comment by dossy** [comment]
I grabbed the tarball for 1.2.0-RC1, and compared it to the commit [4cc7249](https://github.com/w8tvi/dircproxy/commit/4cc72492b9166edaf58695ac924aec4d03106f63) you identified, and I agree:

```
$ git reset --hard 4cc7249
HEAD is now at 4cc7249 Updating URL, Copyright, Typo, SSL mention, ChangeLog, and moving in Release Candidate ...

$ diff -ur ../dircproxy-1.2.0-RC1 . --exclude .git --exclude .svn
Only in ../dircproxy-1.2.0-RC1: Makefile.in
Only in ../dircproxy-1.2.0-RC1: aclocal.m4
Only in ../dircproxy-1.2.0-RC1: autom4te.cache
Only in ../dircproxy-1.2.0-RC1/conf: Makefile.in
Only in ../dircproxy-1.2.0-RC1: config.h.in
Only in ../dircproxy-1.2.0-RC1: configure
Only in ../dircproxy-1.2.0-RC1/contrib: Makefile.in
Only in ../dircproxy-1.2.0-RC1/crypt: Makefile.in
Only in ../dircproxy-1.2.0-RC1: depcomp
Only in ../dircproxy-1.2.0-RC1/doc: Makefile.in
Only in ../dircproxy-1.2.0-RC1/getopt: Makefile.in
Only in ../dircproxy-1.2.0-RC1: install-sh
Only in ../dircproxy-1.2.0-RC1: missing
Only in ../dircproxy-1.2.0-RC1/src: Makefile.in
```

I've gone ahead and created the tag.  Thanks!

**Comment by ryandesign** [comment]
Thanks! You could also create a GitHub "release" for this tag. Then you would have a place where you could attach that original tarball. It's still available from Google Code, but since the Google Code page redirects here there's no way for anybody to discover that.

**Comment by dossy** [comment]
@ryandesign Ah, good idea, for when eventually the Google Code artifacts are finally no longer accessible.

I've gone ahead and created the release and uploaded the tarball to it:

https://github.com/w8tvi/dircproxy/releases/tag/RELEASE-1_2_0-RC1
